//
// HTHowToItemBuilder.m
// HowTo
//
// Copyright (c) 2012 Antoine d'Otreppe. All rights reserved.
//
// Generated by EntityMaker on 18/09/12.
// See http://github.com/aspyct/EntityMaker
//

#import "HTHowToItemBuilder.h"

@implementation HTHowToItemBuilder

@synthesize howToItem = _howToItem;

- (id)init {
    self = [super init];
    
    if (self) {
        _howToItem = [[HTHowToItem alloc] init];
    }
    
    return self;
}

- (void)setId:(NSInteger)id {
    _howToItem->_id = id;
}

- (void)setTitle:(NSString *)title {
    _howToItem->_title = title;
}

- (void)setAuthor:(NSString *)author {
    _howToItem->_author = author;
}

- (void)setImage:(NSURL *)image {
    _howToItem->_image = image;
}

- (void)setDescription:(NSString *)description {
    _howToItem->_description = description;
}

- (void)setScore:(NSInteger)score {
    _howToItem->_score = score;
}

- (void)setTags:(NSSet *)tags {
    _howToItem->_tags = [[NSMutableSet alloc] initWithSet:tags];
}

- (void)setComments:(NSArray *)comments {
    _howToItem->_comments = [[NSMutableArray alloc] initWithArray:comments];
}

- (void)setPublication:(NSDate *)publication {
    _howToItem->_publication = publication;
}

@end
