//
// HTHowToItem.h
// HowTo
//
// Generated by EntityMaker on 18/09/12.
// Copyright (c) 2012 Antoine d'Otreppe. All rights reserved.
//
// EntityMaker, http://github.com/aspyct/EntityMaker
//

#import <Foundation/Foundation.h>

@interface HTHowToItem : UITableView <UITableViewDelegate, UITableViewDataSource> {
@package
    NSInteger _id;
    NSString * _title;
    NSString * _author;
    NSURL * _image;
    NSString * _description;
    NSInteger _score;
    NSMutableSet * _tags;
    NSMutableArray * _comments;
    NSDate * _publication;
}

@property (readonly) NSInteger id;
@property (readonly) NSString * title;
@property (readonly) NSString * author;
@property (readonly) NSURL * image;
@property (readonly) NSString * description;
@property (readonly) NSInteger score;
@property (readonly) NSSet * tags;
@property (readonly) NSArray * comments;
@property (readonly) NSDate * publication;

@end
