//
// MPAuthorBuilder.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>
#import "MPAuthor.h"

@interface MPAuthorBuilder : NSObject

@property (readonly) MPAuthor *author;

- (id)init;

- (void)setAuthorId:(NSInteger)authorId;
- (void)setName:(NSString *)name;

@end
