//
// MPAuthor.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPAuthor.h"

@implementation MPAuthor

@synthesize authorId = _authorId;
@synthesize name = _name;

@end
