//
// MPAuthor.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>

@interface MPAuthor : NSObject {
@package
    NSInteger _authorId;
    NSString * _name;
}

@property (readonly) NSInteger authorId;
@property (readonly) NSString * name;

@end
