//
// MPAuthorBuilder.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPAuthorBuilder.h"

@implementation MPAuthorBuilder

@synthesize author = _author;

- (id)init {
    self = [super init];
    
    if (self) {
        _author = [[MPAuthor alloc] init];
    }
    
    return self;
}

- (void)setAuthorId:(NSInteger)authorId {
    _author->_authorId = authorId;
}

- (void)setName:(NSString *)name {
    _author->_name = name;
}

@end
