//
// MPBlogPostBuilder.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPBlogPostBuilder.h"

@implementation MPBlogPostBuilder

@synthesize blogPost = _blogPost;

- (id)init {
    self = [super init];
    
    if (self) {
        _blogPost = [[MPBlogPost alloc] init];
    }
    
    return self;
}

- (void)setBlogPostId:(NSInteger)blogPostId {
    _blogPost->_blogPostId = blogPostId;
}

- (void)setTitle:(NSString *)title {
    _blogPost->_title = title;
}

- (void)setBody:(NSString *)body {
    _blogPost->_body = body;
}

- (void)setPublicationDate:(NSDate *)publicationDate {
    _blogPost->_publicationDate = publicationDate;
}

- (void)setTags:(NSSet *)tags {
    _blogPost->_tags = [[NSMutableSet alloc] initWithSet:tags];
}

- (void)setComments:(NSArray *)comments {
    _blogPost->_comments = [[NSMutableArray alloc] initWithArray:comments];
}

- (void)setOnline:(NSURL *)online {
    _blogPost->_online = online;
}

@end
