//
// MPBlogPost.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPBlogPost.h"

@implementation MPBlogPost

@synthesize blogPostId = _blogPostId;
@synthesize title = _title;
@synthesize body = _body;
@synthesize publicationDate = _publicationDate;
@synthesize tags = _tags;
@synthesize comments = _comments;
@synthesize online = _online;
@synthesize author = _author;
@synthesize test = _test;

- (id)init
{
    self = [super init];
    
    if (self) {
        _tags = [[NSMutableSet alloc] init];
        _comments = [[NSMutableArray alloc] init];
    }
    
    return self;
}

@end
