//
// MPBlogPost.m
// MyProject
//
// Generated by EntityMaker on 18/09/12.
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// EntityMaker, http://github.com/aspyct/EntityMaker
//

#import "MPBlogPost.h"

@implementation MPBlogPost
@synthesize blogPostId = _blogPostId;
@synthesize title = _title;
@synthesize body = _body;
@synthesize publicationDate = _publicationDate;
@synthesize tags = _tags;
@synthesize comments = _comments;
@synthesize online = _online;

- (id)init
{
    self = [super init];
    
    if (self) {
        _tags = [[NSMutableSet alloc] init];
        _comments = [[NSMutableArray alloc] init];
    }
    
    return self;
}

@end
