//
// MPBlogPost.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>

@interface MPBlogPost : NSObject <AnyProtocol> {
@package
    NSInteger _blogPostId;
    NSString * _title;
    NSString * _body;
    NSDate * _publicationDate;
    NSMutableSet * _tags;
    NSMutableArray * _comments;
    NSURL * _online;
    MPAuthor _author;
    NSObject * _test;
}

@property (readonly) NSInteger blogPostId;
@property (readonly) NSString * title;
@property (readonly) NSString * body;
@property (readonly) NSDate * publicationDate;
@property (readonly) NSSet * tags;
@property (readonly) NSArray * comments;
@property (readonly) NSURL * online;
@property (readonly) MPAuthor author;
@property (readonly) NSObject * test;

@end
