//
// MPComment.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPComment.h"

@implementation MPComment

@synthesize commentId = _commentId;
@synthesize body = _body;
@synthesize author = _author;

@end
