//
// MPCommentBuilder.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by EntityMaker on 18/09/12.
// See http://github.com/aspyct/EntityMaker
//

#import <Foundation/Foundation.h>
#import "MPComment.h"

@interface MPCommentBuilder : NSObject

@property (readonly) MPComment *comment;

- (id)init;

- (void)setCommentId:(NSInteger)commentId;
- (void)setBody:(NSString *)body;
- (void)setAuthor:(NSString *)author;

@end
