//
// MPComment.m
// MyProject
//
// Generated by EntityMaker on 18/09/12.
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// EntityMaker, http://github.com/aspyct/EntityMaker
//

#import "MPComment.h"

@implementation MPComment

@synthesize commentId = _commentId;
@synthesize body = _body;
@synthesize author = _author;

@end
