//
// MPCommentBuilder.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>
#import "MPComment.h"

@interface MPCommentBuilder : NSObject

@property (readonly) MPComment *comment;

- (id)init;

- (void)setCommentId:(NSInteger)commentId;
- (void)setBody:(NSString *)body;
- (void)setAuthor:(NSString *)author;

@end
