//
// MPCommentBuilder.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by EntityMaker on 18/09/12.
// See http://github.com/aspyct/EntityMaker
//

#import "MPCommentBuilder.h"

@implementation MPCommentBuilder

@synthesize comment = _comment;

- (id)init {
    self = [super init];
    
    if (self) {
        _comment = [[MPComment alloc] init];
    }
    
    return self;
}

- (void)setCommentId:(NSInteger)commentId {
    _comment->_commentId = commentId;
}

- (void)setBody:(NSString *)body {
    _comment->_body = body;
}

- (void)setAuthor:(NSString *)author {
    _comment->_author = author;
}

@end
