//
// MPComment.h
// MyProject
//
// Generated by EntityMaker on 18/09/12.
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// EntityMaker, http://github.com/aspyct/EntityMaker
//

#import <Foundation/Foundation.h>

@interface MPComment : NSObject {
@package
    NSInteger _commentId;
    NSString * _body;
    NSString * _author;
}

@property (readonly) NSInteger commentId;
@property (readonly) NSString * body;
@property (readonly) NSString * author;

@end
