//
// MPMutableAuthor.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPMutableAuthor.h"

@implementation MPMutableAuthor

- (void)setAuthorId:(NSInteger)authorId {
    _authorId = authorId;
}

- (void)setName:(NSString *)name {
    _name = name;
}


@end
