//
// MPMutableBlogPost.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>
#import "MPBlogPost.h"

@interface MPMutableBlogPost : MPBlogPost

@property (readwrite) NSInteger blogPostId;
@property (readwrite) NSString * title;
@property (readwrite) NSString * body;
@property (readwrite) NSDate * publicationDate;
@property (readwrite) NSSet * tags;
@property (readwrite) NSArray * comments;
@property (readwrite) NSURL * online;
@property (readwrite) MPAuthor * author;

@end
