//
// MPMutableBlogPost.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPMutableBlogPost.h"

@implementation MPMutableBlogPost

- (void)setBlogPostId:(NSInteger)blogPostId {
    _blogPostId = blogPostId;
}

- (void)setTitle:(NSString *)title {
    _title = title;
}

- (void)setBody:(NSString *)body {
    _body = body;
}

- (void)setPublicationDate:(NSDate *)publicationDate {
    _publicationDate = publicationDate;
}

- (void)setTags:(NSSet *)tags {
    _tags = [[NSMutableSet alloc] initWithSet:tags];
}

- (void)setComments:(NSArray *)comments {
    _comments = [[NSMutableArray alloc] initWithArray:comments];
}

- (void)setOnline:(NSURL *)online {
    _online = online;
}

- (void)setAuthor:(MPAuthor *)author {
    _author = author;
}


@end
