//
// MPMutableAuthor.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>
#import "MPAuthor.h"

@interface MPMutableAuthor : MPAuthor

@property (readwrite) NSInteger authorId;
@property (readwrite) NSString * name;

@end
