//
// MPMutableComment.h
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import <Foundation/Foundation.h>
#import "MPComment.h"

@interface MPMutableComment : MPComment

@property (readwrite) NSInteger commentId;
@property (readwrite) NSString * body;
@property (readwrite) NSString * author;

@end
