//
// MPMutableComment.m
// MyProject
//
// Copyright (c) 2012 MyCompany. All rights reserved.
//
// Generated by ModelMaker
// See http://github.com/aspyct/ModelMaker
//

#import "MPMutableComment.h"

@implementation MPMutableComment

- (void)setCommentId:(NSInteger)commentId {
    _commentId = commentId;
}

- (void)setBody:(NSString *)body {
    _body = body;
}

- (void)setAuthor:(NSString *)author {
    _author = author;
}


@end
